name: Yocto Build

on:
  push:
    branches:
      - '**'  # Matches all branches

jobs:
  yocto-build:
    runs-on: ubuntu-latest
    env:
      YOCTO_BRANCH: kirkstone

    steps:
    - name: Checkout meta layer
      uses: actions/checkout@v3
      with:
        path: yocto-build/meta-sysele-nxp

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gawk wget git diffstat unzip texinfo gcc build-essential \
        chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
        iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm \
        python3-subunit mesa-common-dev zstd liblz4-tool

    - name: Setup Yocto
      run: |
        cd yocto-build
        
        # Clone each layer
        echo "Cloning poky..."
        git clone -b $YOCTO_BRANCH git://git.yoctoproject.org/poky
        
        echo "Cloning meta-openembedded..."
        git clone -b $YOCTO_BRANCH git://git.openembedded.org/meta-openembedded
        
        echo "Cloning meta-arm..."
        git clone -b $YOCTO_BRANCH git://git.yoctoproject.org/meta-arm

    - name: Configure and Build
      run: |
        cd yocto-build/poky
        source oe-init-build-env build
        
        # Get absolute paths
        WORKSPACE_PATH=$(cd ../.. && pwd)
        
        # Add layers to bblayers.conf using absolute paths
        cat << EOF >> conf/bblayers.conf
        BBLAYERS += "${WORKSPACE_PATH}/meta-openembedded/meta-oe"
        BBLAYERS += "${WORKSPACE_PATH}/meta-arm/meta-arm"
        BBLAYERS += "${WORKSPACE_PATH}/meta-arm/meta-arm-toolchain"
        BBLAYERS += "${WORKSPACE_PATH}/meta-sysele-nxp"
        EOF
        
        # Configure local.conf
        cat << EOF >> conf/local.conf
        MACHINE = "your-machine-name"
        DISTRO = "poky"
        DL_DIR = "${WORKSPACE_PATH}/downloads"
        SSTATE_DIR = "${WORKSPACE_PATH}/sstate-cache"
        BB_NUMBER_THREADS = "4"
        PARALLEL_MAKE = "-j 4"
        EOF
        
        # Print configurations for debugging
        echo "Current working directory:"
        pwd
        echo "Workspace path:"
        echo $WORKSPACE_PATH
        echo "Directory structure:"
        ls -la $WORKSPACE_PATH
        echo "Layers configuration:"
        cat conf/bblayers.conf
        
        # Start the build
        bitbake core-image-minimal

    - name: Archive artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: yocto-build-artifacts
        path: yocto-build/poky/build/tmp/deploy/images/**/*
