name: Yocto Build

on:
  push:
    branches:
      - '**'  # Matches all branches

jobs:
  yocto-build:
    runs-on: ubuntu-latest
    env:
      YOCTO_BRANCH: kirkstone
      IMX_BRANCH: lf-6.1.22-2.0.0  # Add specific branch for meta-imx

    steps:
    - name: Create directory structure
      run: |
        mkdir -p yocto-build/sources
        mkdir -p yocto-build/sources-extra

    - name: Checkout meta layer
      uses: actions/checkout@v3
      with:
        path: yocto-build/sources-extra/meta-sysele-nxp

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gawk wget git diffstat unzip texinfo gcc build-essential \
        chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
        iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm \
        python3-subunit mesa-common-dev zstd liblz4-tool

    - name: Clone layers
      run: |
        cd yocto-build/sources
        
        # Core layers
        git clone -b $YOCTO_BRANCH git://git.yoctoproject.org/poky
        git clone -b $YOCTO_BRANCH git://git.openembedded.org/meta-openembedded
        git clone -b $YOCTO_BRANCH https://github.com/Freescale/meta-freescale.git
        git clone -b $YOCTO_BRANCH https://github.com/Freescale/meta-freescale-3rdparty.git
        git clone -b $YOCTO_BRANCH https://github.com/Freescale/meta-freescale-distro.git
        
        # i.MX specific layers - using IMX_BRANCH
        git clone -b $IMX_BRANCH https://github.com/nxp-imx/meta-imx.git
        git clone -b $IMX_BRANCH https://source.codeaurora.org/external/imx/meta-nxp-demo-experience
        
        # Additional required layers
        git clone -b $YOCTO_BRANCH https://github.com/OSSystems/meta-browser.git
        git clone -b $YOCTO_BRANCH https://github.com/kraj/meta-clang.git
        git clone -b $YOCTO_BRANCH https://code.qt.io/yocto/meta-qt6.git
        git clone -b $YOCTO_BRANCH https://git.yoctoproject.org/meta-virtualization

        # Clone Hailo layers
        cd ../sources-extra
        git clone -b $YOCTO_BRANCH https://github.com/hailo-ai/meta-hailo.git

    # Rest of the workflow remains the same...
